$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

type: pipeline
name: Text-Sentiment-test37
display_name: Text Sentiment
experiment_name: Classifying text sentiment

inputs:
  language: "english"
  train_test_split: 20
  data_name: "emotions"
  glove: "glove.6B.200d.txt"
  data_folder: 
    type: uri_folder
    path: azureml:DataFolder:1
  epochs: 10
  batchsize: 126
  valsplit: 20
  patience: 5

outputs:
  model:
    type: uri_folder

settings:
  default_compute: azureml:mlopsc-cli

jobs:
  prepro:
    type: command
    component: ../components/dataprep/prepro.yaml
    inputs:
      data_folder: ${{parent.inputs.data_folder}}
      language: ${{parent.inputs.language}}
      data_name: ${{parent.inputs.data_name}}

    outputs:
      output_data:
        mode: rw_mount
    
  train_test_split:
    type: command
    component: ../components/dataprep/traintest.yaml
    inputs:
      data_folder: ${{parent.jobs.prepro.outputs.output_data}}
      data_name: ${{parent.inputs.data_name}}
      train_test_split: ${{parent.inputs.train_test_split}}
    outputs:
      training_data_output:
        mode: rw_mount
      testing_data_output:
        mode: rw_mount
  
  training:
    type: command
    component: ../components/training/train.yaml
    inputs:
      training_data: ${{parent.jobs.train_test_split.outputs.training_data_output}}
      testing_data: ${{parent.jobs.train_test_split.outputs.testing_data_output}}
      data_name: ${{parent.inputs.data_name}}
      epochs: ${{parent.inputs.epochs}}
      batchsize: ${{parent.inputs.batchsize}}
      valsplit: ${{parent.inputs.valsplit}}
      patience: ${{parent.inputs.patience}}
      glove: ${{parent.inputs.glove}}
      data_folder: ${{parent.inputs.data_folder}}
    outputs:
      output_folder:
        mode: rw_mount
  
  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs: 
      model_name: ${{parent.inputs.data_name}}+classification
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}}
    outputs:
      registration_details_folder: ${{parent.outputs.model}}