$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aml-Training
description: Custom environment for training text data 
version: 0.1.9

conda_file: ../components/training/environments/trainConda.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest