$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aml-DataSplit
description: Custom environment for Data Splitting
version: 0.1.0

conda_file: ../components/dataprep/environments/traintestConda.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
