# Execute as: az ml component create --file .\components\dataprep\prepro.yaml
version: 0.1.0
name: data_split_train_test
type: command
display_name: Splitting data into train and test
description: Reads a csv file and splits it into train and test csv.
inputs:
  data:
    type: uri_folder
    optional: False
  data_name:
    type: string
    optional: False
  train_test_split:
    type: number
    optional: False
outputs:
  training_data_output:
    type: uri_folder
  testing_data_output:
    type: uri_folder
environment: azureml:aml-DataSplit:0.1.0
code: ./code
resources:
  instance_count: 1
command: "python traintest.py --data ${{inputs.data}} --data_name ${{inputs.data_name}} \
   --training_data_output ${{outputs.training_data_output}} --testing_data_output ${{outputs.testing_data_output}}  \
   --split_size ${{inputs.train_test_split}} \
  "